# Music Recommender

In [16]:
from pyspark import SparkContext
import pyspark.sql.functions as F
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from scipy import sparse
from sklearn.metrics.pairwise import cosine_similarity
from time import time

%matplotlib inline

plt.style.use('ggplot')

In [9]:
df = spark.read.csv('../data/event_ds.csv', header=True).cache()

In [10]:
df.show()

+---------+-----+--------+----------+
|      uid|event| song_id|      date|
+---------+-----+--------+----------+
|168551248|    P|21393368|2017-03-30|
|168551026|    P|19477157|2017-03-30|
|168551417|    P|  727161|2017-03-30|
|168551156|    P|  313037|2017-03-30|
|168551179|    P|23485496|2017-03-30|
|168550572|    P| 4297299|2017-03-30|
|168551156|    P|  237508|2017-03-30|
|168548099|    P| 4984002|2017-03-30|
|168549973|    P| 3194852|2017-03-30|
|168548682|    P| 6751795|2017-03-30|
|168549948|    P|23082492|2017-03-30|
|168551120|    P|22858485|2017-03-30|
|168549973|    P| 6461995|2017-03-30|
|168548972|    P|22923154|2017-03-30|
|168551599|    P| 8131487|2017-03-30|
|168551097|    P|23491653|2017-03-30|
|168551417|    P| 6686174|2017-03-30|
|168551576|    P| 3971731|2017-03-30|
|168549643|    P|  848918|2017-03-30|
|168549973|    P|  252181|2017-03-30|
+---------+-----+--------+----------+
only showing top 20 rows

In [12]:
pd.options.display.max_columns = None

In [13]:
pd.read_csv('../data/df_model_final.csv').head()

,uid,label,freq_P_last_1,freq_P_last_3,freq_P_last_7,freq_P_last_14,freq_P_last_30,freq_D_last_1,freq_D_last_3,freq_D_last_7,freq_D_last_14,freq_D_last_30,freq_S_last_1,freq_S_last_3,freq_S_last_7,freq_S_last_14,freq_S_last_30,last_P_from_now,last_S_from_now,last_D_from_now,user_life_length,total_play_times_1,total_play_times_3,total_play_times_7,total_play_times_14,total_play_times_30,device_type
0,118301183,1,0,0,0,0,10,0,0,0,0,0,0,0,0,0,0,27,0,0,28,0.000000,0.000000,0.000000,0.000000,81.048415,2
1,133747174,0,0,0,0,7,40,0,0,0,0,0,0,0,0,2,2,12,12,0,27,0.000000,0.000000,0.000000,24.860476,85.610915,2
2,149292492,1,0,3,3,3,14,0,0,0,0,0,0,0,0,0,0,2,0,0,30,0.000000,23.055643,23.055643,23.055643,60.002599,2
3,154708890,1,0,0,0,0,6,0,0,0,0,0,0,0,0,0,0,20,0,0,30,0.000000,0.000000,0.000000,0.000000,13.302118,2
4,159613840,0,4,51,51,51,51,3,3,3,3,3,1,8,8,8,8,0,0,0,2,12.472836,101.529038,101.529038,101.529038,101.529038,2

### Clean data and get rating data

#### uid, son_id, target(rating)
* play freq over fixed time window
* download freq over fixed time window
* play/song length
* weight different targets, and bucket to levels, eg. 5

In [14]:
import datetime
from dateutil import parser

label_window_size = 14
label_window_end_date = parser.parse('2017-05-12').date()
label_window_start_date = label_window_end_date - datetime.timedelta(label_window_size-1)
print('label window:',label_window_start_date,'~',label_window_end_date,'days:',label_window_size)

feature_window_size = 30
feature_window_end_date = label_window_start_date - datetime.timedelta(1)
feature_window_start_date = feature_window_end_date  - datetime.timedelta(feature_window_size - 1)
print('feature window:',feature_window_start_date,'~',feature_window_end_date,'days:',feature_window_size)

label window: 2017-04-29 ~ 2017-05-12 days: 14
feature window: 2017-03-30 ~ 2017-04-28 days: 30

In [17]:
# all the uid we will model
# df_model_uid = df.filter((F.col('date') >= feature_window_start_date) & \
#                         (F.col('date') <= feature_window_end_date)) \
#                         .select('uid').distinct()

In [ ]:
# define a function to generate frequency features
# def frequency_feature_generation(df, event, time_window, snapshot_date): 
#     """
#     generate frequency features for one event type and one time window
#     """
#     df_feature = df.filter(F.col('event') == event) \
#                 .filter((F.col('date') >= snapshot_date - datetime.timedelta(time_window-1)) & (F.col('date') <= snapshot_date)) \
#                 .groupBy('uid').agg(
#                     F.count(F.col('uid')).alias('freq_'+event+'_last_'+str(time_window))
#                 )
#     return df_feature

In [ ]:
# generate frequency features for all event_list, time_window_list
# event_list = ['P','D','S']
# time_window_list = [1,3,7,14,30]
# df_feature_list = []
# for event in event_list:
#     for time_window in time_window_list:
#         df_feature_list.append(frequency_feature_generation(df_feature_window,event,time_window,snapshot_date))